language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

  allow_failures:
    - php: 5.4
    - php: 5.5

install: composer install

before_script:
  - composer global require satooshi/php-coveralls
  - mysql -u root -e 'CREATE DATABASE test;'
  - psql -c 'create database test;' -U postgres

services:
  - mysql
  - postgresql

matrix:

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/php-coveralls