language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: hhvm
    
  exclude:
    - php: hhvm
      env: DB=pgsql

services:
  - mysql
  - postgresql
  
install: composer install --dev

before_script:
  - mysql -u root -e 'CREATE DATABASE test;'
  - psql -c 'create database test;' -U postgres

script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml.dist

after_success:
  - travis_retry php vendor/bin/php-coveralls
