<?php

namespace Tsukasa\Tests\QueryBuilder\fixtures;

use Tsukasa\QueryBuilder\Aggregation\Aggregation;
use Tsukasa\QueryBuilder\QueryBuilder;

class TestQueryBuilder extends QueryBuilder
{
    public function buildAndCondition($operator, $operands, &$params)
    {
        return parent::buildAndCondition($operator, $operands, $params); // TODO: Change the autogenerated stub
    }

    public function buildCondition($condition, &$params = [])
    {
        return parent::buildCondition($condition, $params); // TODO: Change the autogenerated stub
    }

    public function buildFrom()
    {
        return parent::buildFrom(); // TODO: Change the autogenerated stub
    }

    public function buildGroup()
    {
        return parent::buildGroup(); // TODO: Change the autogenerated stub
    }

    public function buildHaving()
    {
        return parent::buildHaving(); // TODO: Change the autogenerated stub
    }

    public function buildJoin()
    {
        return parent::buildJoin(); // TODO: Change the autogenerated stub
    }

    public function buildLimitOffset()
    {
        return parent::buildLimitOffset(); // TODO: Change the autogenerated stub
    }

    public function buildOrder()
    {
        return parent::buildOrder(); // TODO: Change the autogenerated stub
    }

    public function buildSelect()
    {
        return parent::buildSelect(); // TODO: Change the autogenerated stub
    }

    public function buildGroupJoin($group)
    {
        return parent::buildGroupJoin($group); // TODO: Change the autogenerated stub
    }

    public function buildUnion()
    {
        return parent::buildUnion(); // TODO: Change the autogenerated stub
    }

    public function buildWhere()
    {
        return parent::buildWhere(); // TODO: Change the autogenerated stub
    }

    public function buildWhereTree()
    {
        return parent::buildWhereTree(); // TODO: Change the autogenerated stub
    }

    public function buildSelectFromAggregation(Aggregation $aggregation)
    {
        return parent::buildSelectFromAggregation($aggregation); // TODO: Change the autogenerated stub
    }

    public function buildOrderJoin($order)
    {
        return parent::buildOrderJoin($order); // TODO: Change the autogenerated stub
    }
}